site_name: Meta-Human DNA Addon
nav:
  - Quick Start: "index.md"
  - Terminology: "terminology.md"
  - Face Board: "face-board.md"
  - View Options: "view-options.md"
  - Rig Logic: "rig-logic.md"
  - Shape Keys: "shape-keys.md"
  - Output: "output.md"

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition