
services:
  linux-dev-env:
    image: linux-dev-env:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: sleep
    command: infinity
    volumes:
      - ../../:/tmp/repo

# docker-compose up --build

# /usr/local/bin/python3.11 -m venv .linux-venv
# source ./.venv/bin/activate
# pip install --upgrade -r requirements.txt