name: Create Release

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: Python version for the build
        required: true
        default: '3.11'

permissions:
  contents: write

jobs:
  run_reusable_release:
    uses: ./.github/workflows/re-use-release.yaml
    with:
      python-version: ${{ inputs['python-version'] }}
    secrets: inherit
