name: Create Release

on:
  workflow_dispatch:
    inputs:
      blender-version:
        description: Blender version
        required: true
        default: '4.5'
      python-version:
        description: Python version
        required: true
        default: '3.11'

permissions:
  contents: write

jobs:
  build_addon:
    uses: ./.github/workflows/re-use-release.yaml
    with:
      blender-version: ${{ inputs['blender-version'] }}
      python-version: ${{ inputs['python-version'] }}
    secrets: inherit
