name: Docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  release:
    name: Docs
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade -r requirements.txt

      - name: Create Release
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          DOCS_REPO: ${{ secrets.DOCS_REPO }}
        run: |
          python -m poly_hammer_utils.addon.release docs

      